const products = [
    {
        id: 0,
        name: "T-SHIRT WITH CONTRAST SLOGAN",
        price: 299.00,
        sale: 50,
        new: 1,
        description: "T-shirt",
        imgSrc: "img/productgirl1.jpg",
        instock: 43,
    },
    {
        id: 1,
        name: "EMBROIDERED DINA RAZIN T-SHIRT",
        price: 499.00,
        sale: 50,
        new: 1,
        description: "T-shirt",
        imgSrc: "img/productgirl2.jpg",
        instock: 43,
    },
    {
        id: 2,
        name: "DISNEY'S PINOCCHIO T-SHIRT",
        price: 199.00,
        sale: 0,
        new: 0,
        description: "T-shirt",
        imgSrc: "img/productgirl3.jpg",
        instock: 43,
    },
    {
        id: 3,
        name: "EMBROIDERED SILHOUETTE T-SHIRT",
        price: 599.00,
        sale: 0,
        new: 0,
        description: "T-shirt",
        imgSrc: "img/productgirl4.jpg",
        instock: 43,
    },
    {
        id: 4,
        name: "GIRL PRINT T-SHIRT",
        price: 200.00,
        sale: 0,
        new: 1,
        description: "T-shirt",
        imgSrc: "img/productgirl5.jpg",
        instock: 43,
    },
    {
        id: 5,
        name: "PRINTED POWER LIGHT T-SHIRT",
        price: 299.00,
        sale: 50,
        new: 1,
        description: "T-shirt",
        imgSrc: "img/productman2.jpg",
        instock: 43,
    },
    {
        id: 6,
        name: "T-SHIRT WITH CONTRAST DESIGNS",
        price: 600.00,
        sale: 50,
        new: 1,
        description: "T-shirt",
        imgSrc: "img/productman3.jpg",
        instock: 43,
    },
    {
        id: 7,
        name: ">T-SHIRT WITH A LARISSA DE JESÚS NEGRÓN PRINT",
        price: 100.00,
        sale: 50,
        new: 0,
        description: "T-shirt",
        imgSrc: "img/productman4.jpg",
        instock: 43,
    }
    ,{
        id: 8,
        name: ">T-SHIRT PRINT",
        price: 200.00,
        sale: 50,
        new: 0,
        description: "T-shirt",
        imgSrc: "img/productman5.jpg",
        instock: 43,
    },
];
